# Q2
# Build your own (minimal) dictionary-based filter technique and plot the result

Preparation
```{r, message=F}
library(tidyverse)
library(tidytext)

getwd()
```

Process
```{r, eval = F}
# Load
tweets <- readRDS(gzcon(url("https://github.com/cjbarrie/CTA-ED/blob/main/data/sentanalysis/newstweets.rds?raw=true")))
View(tweets)

# Rename
tweets <- tweets %>%
  select(user_username, text, created_at, user_name,
         retweet_count, like_count, quote_count) %>%
  rename(username = user_username,
         newspaper = user_name,
         tweet = text)

# Lowercase and tokenize
tidy_tweets <- tweets %>% 
  mutate(desc = tolower(tweet)) %>%
  unnest_tokens(word, desc) %>%
  filter(str_detect(word, "[a-z]"))

# Remove stop words
tidy_tweets <- tidy_tweets %>%
    filter(!word %in% stop_words$word)

# Date in ascending order
tidy_tweets <- tidy_tweets %>%
  mutate(date = as.Date(created_at)) %>%
  arrange(date)

View(tidy_tweets)
```

Dictionary-based filter
```{r}
# Dictionary of anxiety
dict_anxiety <- c('anxiety', 'anxious', 'worry', 'worried', 'tense', 'nervous', 'uncomfortable', 'uneasy', 'unsettled', 'stress', 'restless')

# Get total tweets per day
totals <- tidy_tweets %>%
  mutate(obs=1) %>%
  group_by(date) %>%
  summarise(sum_words = sum(obs))

# Calculate the proportion of containing anxiety
proportions <- 
  tidy_tweets %>%
  mutate(obs=1) %>%
  filter(grepl(paste0(dict_anxiety, collapse = "|"), word, ignore.case = TRUE)) %>%
  group_by(date) %>%
  summarise(sum_mwords = sum(obs)) %>%
  full_join(totals, by="date") %>%
  mutate(sum_mwords = ifelse(is.na(sum_mwords), 0, sum_mwords),
         pctmwords = sum_mwords / sum_words)

View(proportions)
```

Plot
```{r}
proportions %>%
ggplot(aes(date, pctmwords)) +
  geom_point(alpha=0.5) +
  geom_smooth(method= loess, alpha=0.25) +
  xlab("Date") + ylab("% Anxiety Words")
```

